### ISSUE TITLE
Hello，不知道可以分享一下checkpoint吗？

### ISSUE THREAD

**Issue by hungsing92** [woodfrog/maptracker#1]

**Comment by woodfrog** [comment]
The checkpoints can be found [here](https://github.com/woodfrog/maptracker/blob/main/docs/data_preparation.md#checkpoints) in the data preparation doc.

**Comment by woodfrog** [comment]
I realized that you might not have access to Dropbox. I uploaded a copy to Microsoft OneDrive [here](https://1sfu-my.sharepoint.com/:f:/g/personal/jca348_sfu_ca/EvLcfTWRrcZPpukRW30sOGoBUVIpSwCz5tvJCmMSGcdW-g?e=wDZ2IN), can you download this one?
