### ISSUE TITLE
Checkpoints for phase1 and phase2

### ISSUE THREAD

**Issue by HongjaeShin** [woodfrog/maptracker#10]
Thank you for your great work.
I would like to reproduce your proposed model, but it seems that the checkpoints posted in data_preparation.md are only for phase3. Is it possible to get checkpoints for phase 1 and 2 as well?

**Comment by woodfrog** [comment]
I'm uploading my stage1 and stage2 checkpoints for nuScenes/Argoverse oldsplit to the same Dropbox folder, you can download them later. However, the best way to reproduce everything is to run the training on your machine.
