### ISSUE TITLE
您好，小白想咨询一下关于代码理解的问题

### ISSUE THREAD

**Issue by 304886938** [woodfrog/maptracker#11]
您好，
按您论文中的意思，鸟瞰图记忆缓存器中已经存储了历史帧的鸟瞰图信息。
但是在代码中，看起来还需要将前几帧的数据再经过Backbone、Neck的处理，然后再对当前帧的环视相机特征进行处理。
按我的理解，应该不需要再处理一遍了，历史帧信息可以直接和当前帧信息进行融合。
请问是我的理解有问题吗？
希望您有空能回复我，非常感谢您！

**Comment by woodfrog** [comment]
可能什么地方理解有点问题。是不需要重复处理前几帧的数据的，每一帧的数据只会过一次backbone和bev encoder。

**Comment by 304886938** [comment]
谢谢您的回复！
我还想请问下，这一部分代码的作用是什么呢？
![forword](https://github.com/woodfrog/maptracker/assets/56421262/00d27df5-7f1f-40d0-8e5f-071577b6267f)

**Comment by woodfrog** [comment]
> 谢谢您的回复！ 我还想请问下，这一部分代码的作用是什么呢？ ![forword](https://private-user-images.githubusercontent.com/56421262/336817045-00d27df5-7f1f-40d0-8e5f-071577b6267f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MzYxMjMsIm5iZiI6MTcxNzYzNTgyMywicGF0aCI6Ii81NjQyMTI2Mi8zMzY4MTcwNDUtMDBkMjdkZjUtN2YxZi00MGQwLThlNWYtMDcxNTc3YjYyNjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAxMDM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMDkyYjhiZmQyN2Y2ZjRhYjQ1MDI3M2JmNjI4MGI3NmE1NWViZjhjNmRmZjRiMDA3ODNjMjA1ZmE2NDFlZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XLHxxQHVWSSO65s7p_uFLUgO2J4iYKAGS94IUF-RH8Q)

这部分是训练的代码。每个iteration会随机sample一个video clip用来训练，我们用的clip长度是5帧(所以你这个截图里num_prev_frames=4)。这5帧会一步步rollout，每一帧只会过一次backbone。

**Comment by 304886938** [comment]
好的好的，谢谢您

**Comment by lebron-2016** [comment]
> > 谢谢您的回复！ 我还想请问下，这一部分代码的作用是什么呢？ ![forword](https://private-user-images.githubusercontent.com/56421262/336817045-00d27df5-7f1f-40d0-8e5f-071577b6267f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MzYxMjMsIm5iZiI6MTcxNzYzNTgyMywicGF0aCI6Ii81NjQyMTI2Mi8zMzY4MTcwNDUtMDBkMjdkZjUtN2YxZi00MGQwLThlNWYtMDcxNTc3YjYyNjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAxMDM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMDkyYjhiZmQyN2Y2ZjRhYjQ1MDI3M2JmNjI4MGI3NmE1NWViZjhjNmRmZjRiMDA3ODNjMjA1ZmE2NDFlZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XLHxxQHVWSSO65s7p_uFLUgO2J4iYKAGS94IUF-RH8Q)
> 
> 这部分是训练的代码。每个iteration会随机sample一个video clip用来训练，我们用的clip长度是5帧(所以你这个截图里num_prev_frames=4)。这5帧会一步步rollout，每一帧只会过一次backbone。

您好，请问您的策略是训练时一个iter循环处理5帧，只计算最后一帧的损失，测试时逐帧迭代吗？
