### ISSUE TITLE
trans_loss error and pred.shape[0]==0

### ISSUE THREAD

**Issue by yj772881654** [woodfrog/maptracker#13]
<img width="688" alt="image" src="https://github.com/woodfrog/maptracker/assets/47414253/2bb809df-0e28-4163-b8b0-7b7137426c78">
<img width="649" alt="image" src="https://github.com/woodfrog/maptracker/assets/47414253/aa497979-53e0-446e-b3df-5513e905f095">
During training, I encountered an error where the pred shape was 0, and the trans loss returned a None error. I have made modifications to get the correct results, but I would like to ask if you have this problem over there. What is the reason?

**Comment by woodfrog** [comment]
I don't remember getting exactly the same error in my own training. Did you get this error at the first few iterations of the training? If yes, I can guess the reason: 

At the very beginning of the training, it's possible that all the outputs have low confidence and no prediction is propagated to the next frame. When this happens, the tracked query has length 0 and will trigger the error you encountered.

**Comment by yj772881654** [comment]
I think you are right, I have another question about the function prepare_track_queries_and_targets. What is the role of track_queries_fal_pos_mask and false positive queries, and how do these differ from the normal track queries?

**Comment by yj772881654** [comment]
I have another question about the function prepare_track_queries_and_targets. What is the role of track_queries_fal_pos_mask and false positive queries, and how do these differ from the normal track queries?
