### ISSUE TITLE
track_queries_fal_pos_mask and  false positive queries

### ISSUE THREAD

**Issue by yj772881654** [woodfrog/maptracker#14]
I have another question about the function prepare_track_queries_and_targets. What is the role of track_queries_fal_pos_mask and false positive queries, and how do these differ from the normal track queries?

**Comment by woodfrog** [comment]
During training, the false positive track queries are some noisy instances that not propagated from the matched positive predictions of the last frame. They are randomly sampled from the negative predictions from the last frame. The goal is to mimic the wrong predictions of the last frame, which naturally happens at test time.  However, we actually turn this off (see the [config](https://github.com/woodfrog/maptracker/blob/main/plugin/configs/maptracker/nuscenes_oldsplit/maptracker_nusc_oldsplit_5frame_span10_stage3_joint_finetune.py#L80)) following [MOTRv2](https://arxiv.org/abs/2211.09791)'s practices (See Sec4.2 of their paper).

**Comment by yj772881654** [comment]
Thank you for your response; it resolved my doubts. I have another question. Where are the Deformable Self Attention and Perspective-to-BEV Cross Attention in the BEV Module implemented? I don't seem to see the relevant content in MapTracker.py.

**Comment by woodfrog** [comment]
> Thank you for your response; it resolved my doubts. I have another question. Where are the Deformable Self Attention and Perspective-to-BEV Cross Attention in the BEV Module implemented? I don't seem to see the relevant content in MapTracker.py.

Those are in the [bevformer folder](https://github.com/woodfrog/maptracker/blob/main/plugin/models/backbones/bevformer/encoder.py#L222)
