### ISSUE TITLE
Where is Nuscene lines coordinate frame?

### ISSUE THREAD

**Issue by mmahdavian** [woodfrog/maptracker#17]
Hello. I am using Nuscenes to get line vectors using the map extractor. I am checking this function:
`map_geoms = self.map_extractor.get_map_geom(location, lidar2global_translation, lidar2global_rotation)
`
The location is map name and the next two inputs are global lidar translation and rotation. The map_geoms contains LineStrings in shapely format and I need to know the global coordinate frames of the lines. Are they defined with respect to ego vehicle or the global map coordinate frame? Also, do you know how exactly I can get all the line point values?

Thank You

**Comment by woodfrog** [comment]
All the polyline/polygon geometries are obtained by [querying](https://github.com/woodfrog/maptracker/blob/e3c603fe10c174581838c0716636df9da5fb85c9/plugin/datasets/map_utils/nuscmap_extractor.py#L180) the [map API](https://github.com/woodfrog/maptracker/blob/e3c603fe10c174581838c0716636df9da5fb85c9/plugin/datasets/map_utils/nuscmap_extractor.py#L34) of nuScenes. The way those APIs are queried is defined by the [nuscenes-devkit library](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/map_expansion/map_api.py#L671). 

The map_geoms here should be in the lidar coordinate frame, but you can convert them to other coordinate frames as all transformation matrices are there. For your last question, I'm not sure if you are asking about "geom.coords", you should check Shapely's API doc as well.
