### ISSUE TITLE
能否提供训练日志

### ISSUE THREAD

**Issue by canteen-man** [woodfrog/maptracker#18]
我单卡batch size是6的情况，预估训练3步大概要一个月的时间，不知道能否提供训练日志，可以提前知道loss训练到多少是已经收敛。

**Comment by woodfrog** [comment]
单卡是很慢。而且bs=6，如果你的server cpu资源/IO读写速度一般的话，可能data loading会很慢。multi-view+multi frame导致IO负担比较重。最后一个stage只跑一半epoch效果不会差很多。或者也可以只跑前两个stage来调试。

**Comment by canteen-man** [comment]
你好，方便透露你用的是什么型号的cpu吗，我服务器是两个E5，cpu所有线程轻松都拉满。我想如果可能，就换一组cpu，谢谢。

**Comment by woodfrog** [comment]
我之前跑实验用的8x24G A5000 server是这样
<img width="512" alt="image" src="https://github.com/user-attachments/assets/0eaabf8a-a9fd-47ff-9806-19c5970dec26">
