### ISSUE TITLE
Why lidar coordinate frame?

### ISSUE THREAD

**Issue by mmahdavian** [woodfrog/maptracker#20]
Hi. I was wondering what was the reason that you converted ego coordinate frame to lidar? Why didn't you use ego coordinate frame for e2g_translation and e2g_rotation?

Thank You

**Comment by woodfrog** [comment]
This is because we follow MapTR's choice of coordinate frame so that the comparison can be fair (under the same coordinate system). This was explained in Sec4.1 of the paper.
