### ISSUE TITLE
num_iters_per_epoch in config files?

### ISSUE THREAD

**Issue by mmahdavian** [woodfrog/maptracker#21]
Hi. I was wondering where the 27846  number comes from in the config file?
num_iters_per_epoch = 27846 // (num_gpus * batch_size)

What happens if we pick a smaller number? Does it miss some part of the dataset? Or it is actually randomly picking the data and it's fine?

Thank You

**Comment by kinjonun** [comment]
Hello, I have a similar question. Why is the num iters_per_epoch different in stage1 and stage2? For example, in av2 newsplits stage1 is 29293, and stage2/3 is 27243?  
Thank You

**Comment by woodfrog** [comment]
> Hello, I have a similar question. Why is the num iters_per_epoch different in stage1 and stage2? For example, in av2 newsplits stage1 is 29293, and stage2/3 is 27243? Thank You

Good catch. The `num_iters_per_epoch` should be the same for the same training data (it's the number of training frames in the training set). For av2 newsplit, the stage2/3's configs were copied and adapted from the oldsplit configs and I forgot to update that number. The model was trained for slightly less iterations than expected in stage2/3.

**Comment by woodfrog** [comment]
I made an update in commit 684494b to align the number of samples with the exact number of training frames for each dataset split.
