### ISSUE TITLE
Training with multiple nodes

### ISSUE THREAD

**Issue by mmahdavian** [woodfrog/maptracker#22]
Hello. I see you have the capability to train the model with multiple GPUs. Does the code also have the capability of being trained with multiple nodes of GPUs? So we can increase the number of GPUs we use in parallel?

Thank You
Bests,

**Comment by woodfrog** [comment]
We didn't do multi-node training in our experiments. But the codebase is based on [mmdetection](https://github.com/open-mmlab/mmdetection), and you can check their official doc for multi-node training, I think their launch script is [here](https://github.com/open-mmlab/mmdetection/blob/master/tools/dist_train.sh).
