### ISSUE TITLE
Different evaluation results on nuscenes

### ISSUE THREAD

**Issue by wenjie710** [woodfrog/maptracker#24]
Thanks for the source code! 

Using the provided checkpoint ('maptracker_nusc_newsplit_5frame_span10_stage3_joint_finetune.zip'), I am seeing abnormally high results on nuScenes. 
+--------------+-----------+---------+--------+--------+--------+--------+
|   category   | num_preds | num_gts | AP@0.5 | AP@1.0 | AP@1.5 |   AP   |
+--------------+-----------+---------+--------+--------+--------+--------+
| ped_crossing |   172384  |   6922  | 0.8986 | 0.9445 | 0.963  | 0.9354 |
|   divider    |   206685  |  27332  | 0.8669 | 0.9067 | 0.9251 | 0.8996 |
|   boundary   |   274814  |  21050  | 0.8177 | 0.8919 | 0.9331 | 0.8809 |
+--------------+-----------+---------+--------+--------+--------+--------+
mAP_normal = 0.9053 

Do you know why this happens?

**Comment by woodfrog** [comment]
Hi, based on the num_gts in your log, it seems that you are testing on the oldsplit using the newsplit checkpoint. You can get the correct results by aligning the checkpoint and the dataset setting.

I didn't check it, but It is possible that many test scenes in the old split belong to the training set in the new split. You can refer to StreamMapNet, which proposes the new split, for complete details. My coauthor will run the evaluation using your setting to confirm and reach back to you later.

**Comment by Iven-Wu** [comment]
I reviewed the results again, and it appears that evaluating the 'newsplit' checkpoint on the old split produces these outcomes. You may need to switch to the correct checkpoint for proper evaluation.
