### ISSUE TITLE
[BUG] average_precision in plugin/datasets/evaluation/AP.py

### ISSUE THREAD

**Issue by TangAL0203** [woodfrog/maptracker#26]
when mode == '11points', this line "precs = precisions[0, recalls[i, :] >= thr]", var i has no reference

**Comment by woodfrog** [comment]
Thanks for the catch. This "11points" mode is not really used in the evaluation. That part of the code is directly inherited from StreamMapNet's codebase, and the mode is always "area". I wonder how did you trigger that error?

**Comment by TangAL0203** [comment]
Oh, I didn't encounter this error, I just found this piece missing when reading the code, so I was curious about how 11-points was implemented.
