### ISSUE TITLE
关于正负样本分配的问题？只考虑了分类损失

### ISSUE THREAD

**Issue by TangAL0203** [woodfrog/maptracker#28]
plugin/models/assigner/assigner.py#L133，进行匈牙利匹配时，只考虑了分类损失，没考虑回归损失，是故意的还是bug啊？
```python
matched_row_inds, matched_col_inds = linear_sum_assignment(cost)
```

**Comment by woodfrog** [comment]
两种都有呀. cost的代码在[这里](https://github.com/woodfrog/maptracker/blob/main/plugin/models/assigner/match_cost.py#L365), 然后这个是对应的[config](https://github.com/woodfrog/maptracker/blob/main/plugin/configs/maptracker/nuscenes_oldsplit/maptracker_nusc_oldsplit_5frame_span10_stage3_joint_finetune.py#L239)

**Comment by TangAL0203** [comment]
噢，SRY，看岔了，确实是有的。
