### ISSUE TITLE
strange evaluation results.

### ISSUE THREAD

**Issue by Jctrp** [woodfrog/maptracker#31]
Hi!
After I ran the 'Inference and evaluate with Chamfer-based mAP' step, I obtained some strange evaluation results. Is this normal?
![图片](https://github.com/user-attachments/assets/9cc9003d-42dc-4cb1-aaf7-24e5298b1b73)
Is this because my dataset is incomplete or are there some other issues that I haven't noticed?

**Comment by woodfrog** [comment]
Hi, I think you might run into the same issue as #24. You need to evaluate the model with the corresponding dataset split.

**Comment by Jctrp** [comment]
Thank you for your response!
In fact, I have already conducted the tests using the 'latest.pth' from the old_split along with the corresponding configuration files, and the results I mentioned are based on this old_split setup.
I will try running the evaluations under the new_split conditions as well and see if it runs correctly:(

**Comment by woodfrog** [comment]
I see. The num_preds and num_gts look very small. Can you make sure you evaluated on the entire validation set?

**Comment by Jctrp** [comment]
Hi! Yes, you're right, and I'm also quite puzzled by this.
I tried the new_split version and obtained the following results:
![图片](https://github.com/user-attachments/assets/babee8d7-9852-4c98-89c8-f31382b38af6)
These seem to be in line with the reported conclusions. 
It appears that there might have been some undiscovered issues with the setup when I was running the old_split.

**Comment by edautumn** [comment]
I encountered the same problem in oldsplit. Did you find out where the problem is later?

> Thank you for your response! In fact, I have already conducted the tests using the 'latest.pth' from the old_split along with the corresponding configuration files, and the results I mentioned are based on this old_split setup. I will try running the evaluations under the new_split conditions as well and see if it runs correctly:(
