### ISSUE TITLE
Show results

### ISSUE THREAD

**Issue by LIvanoff** [woodfrog/maptracker#7]
I got the following error when running testing on one device

python .\tools\test.py  plugin/configs/maptracker/nuscenes_oldsplit/maptracker_nusc_oldsplit_5frame_span10_stage3_joint_finetune.py    work_dirs/pretrained_ckpts/maptracker_nusc_oldsplit_5frame_span10_stage3_joint_finetune/latest.pth  --show

[                                                  ] 0/6019, elapsed: 0s, ETA:Traceback (most recent call last):
  File ".\tools\test.py", line 262, in <module>
    main()
  File ".\tools\test.py", line 233, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "e:\pycharmprojects\maptracker\mmdetection3d\mmdet3d\apis\test.py", line 58, in single_gpu_test
    if batch_size == 1 and isinstance(data['img'][0],
TypeError: 'DataContainer' object is not subscriptable

**Comment by woodfrog** [comment]
Please follow our [guide](https://github.com/woodfrog/maptracker/blob/main/docs/getting_started.md) to run the testing and visualization. It seems that your command is not correct.
